// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbV6LmdfwZTtNmeJuqdMVYgDHV-Pn1xNk',
    appId: '1:438717342001:ios:28100b2b4d6b6bc11d9010',
    messagingSenderId: '438717342001',
    projectId: 'georeminders-dcef9',
    storageBucket: 'georeminders-dcef9.firebasestorage.app',
    iosClientId: '438717342001-19i27s2ns10ttnltnrecg858thfbibs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoReminders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbV6LmdfwZTtNmeJuqdMVYgDHV-Pn1xNk',
    appId: '1:438717342001:ios:4201725bd2a45f7a1d9010',
    messagingSenderId: '438717342001',
    projectId: 'georeminders-dcef9',
    storageBucket: 'georeminders-dcef9.firebasestorage.app',
    iosClientId: '438717342001-85m1q9lp18708qhqo26gdl8jkm2p92j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.geocalendarGt',
  );

}